### ISSUE TITLE
Can this work with Rmarkdown template?

### ISSUE THREAD

**Issue by sasutils** [openanalytics/patientProfilesVis#1]
We are having trouble getting this to work with Rstudio Pro and a stable R installation because of the use the imakeidx.sty in the template.

How could this be adapted to work with Rmarkdown documents?

**Comment by lcougnaud** [comment]
Thanks for your interest in the package!
Which platform do you use (Windows/Linux/Mac)? 
If you work on Linux, could you try to install the `texlive-latex-extra` package (see [Docker file](https://github.com/openanalytics/patientProfilesVis/blob/master/Dockerfile#L25)), which contains the file `imakeidx.sty`?

**Comment by lcougnaud** [comment]
I will close the issue, as there was no answer on the previous answer. 
Feel free to re-open it (with a reproducible example if possible) if this is still an issue.
