### ISSUE TITLE
Issue with ggplot2 3.4.0

### ISSUE THREAD

**Issue by thomasp85** [openanalytics/patientProfilesVis#6]
Hi

We recently released ggplot2 3.4.0 and while we didn’t detect issues with cocktailApp during our tests, CRAN has seen issues after release. This mail is to notify you about this and offer help if there are any issues you have trouble fixing

Kind regards
Thomas Lin Pedersen, ggplot2 maintainer

**Comment by lcougnaud** [comment]
Thanks for the heads-up!
The package has been updated to deal with the new ggplot2 version (3.4.0) in a new version: 2.0.5 - available in CRAN since the 18/11.
